// CPP - PRACTICE: CONTINUE
// VERILOG I2C, UART COMPLETION
// SPEC READING / REVISION
// DIGITAL DESIGN REVISION + PRACTICE
// QUEUE IN CPP
// FIFO ADDITIONAL FEATURE (CIRCULAR ASYNCH)
//
//
//
//
// P1: CPP PRACTICE (ongoing course + self - practice)
